package com.github.koen_mulder.file_rename_helper.app;

public enum EConfigIdentifier {
    FILENAME_PROMPT, ADDITIONAL_FILENAME_PROMPT, MODEL_NAME, OLLAMA_ENDPOINT,
    EMBEDDING_STORE_FILE_PATH, KEYWORDS_PROMPT, ADDITIONAL_KEYWORDS_PROMPT, DATES_PROMPT,
    ADDITIONAL_DATES_PROMPT, FILEPATH_PROMPT, ADDITIONAL_FILEPATH_PROMPT, SYSTEM_MESSAGE;
}
