/**
 * 
 */
package com.github.koen_mulder.file_rename_helper.interfaces;

/**
 * The FormClearPublisher interface is implemented by components that tell other components to clear their form fields.
 */
public interface FormClearPublisher {
    /**
     * Adds a listener that will be notified when to clear itself.
     * 
     * @param listener The listener to be added.
     */
    void addFormClearListener(FormClearListener listener);

    /**
     * Removes a previously added listener.
     * 
     * @param listener The listener to be removed.
     */
    void removeFormClearListener(FormClearListener listener);

    /**
     * Notifies all registered listeners of the clear form event.
     * 
     * @param suggestions generated by the LLM.
     */
    void notifyFormClearListeners();
}
