/**
 * 
 */
package com.github.koen_mulder.file_rename_helper.interfaces;

/**
 * The FormClearListener interface is implemented by components that should
 * clear their form fields. Clear form events are published by a
 * {@link SuggestionPublisher}.
 */
public interface FormClearListener {
    /**
     * This method will be called when the panel component should clear it's fields.
     * 
     * @param suggestions generated by the LLM.
     */
    void onClearFormEvent();

}
