/**
 * 
 */
package com.github.koen_mulder.file_rename_helper.interfaces;

import com.github.koen_mulder.file_rename_helper.controller.AIController.FilenameSuggestions;

/**
 * The SuggestionPublisher interface is implemented by classes that manage 
 * the filename suggestion process and notify registered {@link SuggestionListener}s when new suggestions have been made
 */
public interface SuggestionPublisher {
    /**
     * Adds a listener that will be notified when suggestions are made.
     * 
     * @param listener The listener to be added.
     */
    void addSuggestionListener(SuggestionListener listener);

    /**
     * Removes a previously added listener.
     * 
     * @param listener The listener to be removed.
     */
    void removeSuggestionListener(SuggestionListener listener);

    /**
     * Notifies all registered listeners of the filename suggestion event.
     * 
     * @param suggestions generated by the LLM.
     */
    void notifySuggestionListeners(FilenameSuggestions suggestions);
}
