/**
 * 
 */
package com.github.koen_mulder.file_rename_helper.interfaces;

import com.github.koen_mulder.file_rename_helper.controller.AIController.FilenameSuggestions;

/**
 * The SuggestionListener interface is implemented by components that need to
 * react to suggestion events of a {@link SuggestionPublisher}.
 */
public interface SuggestionListener {
    /**
     * This method will be called when suggestions are added in the {@link SuggestionPublisher}.
     * 
     * @param suggestions generated by the LLM.
     */
    void onSuggestionsGenerated(FilenameSuggestions suggestions);

}
