name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'  # Trigger on tags starting with 'v' (e.g., v1.0.0)
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
      with:  # Add this 'with' block
        fetch-depth: 0  # Fetch all history for all tags and branches

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for all tags and branches

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

  create-release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needs write access to create releases

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

    - name: Build with Gradle Wrapper (for artifacts)
      run: ./gradlew build

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/libs/*  # Upload the JAR files from the build
        name: Release ${{ github.ref_name }}  # Use the tag name as the release title
        body: |  # You can customize the release body
          This is release ${{ github.ref_name }} of file-rename-helper.
          See the commit history for details.
        draft: true   # Set to true if you want to manually review before publishing
        prerelease: false  # Set based on your versioning (e.g., if you have a -rc tag)
        dry_run: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use the built-in token
